[package]
name = "rat-menu"
version = "0.32.0"
edition = "2021"
authors = ["thscharler <thscharler@gmail.com>"]
description = "menu widgets for ratatui"
license = "MIT/Apache-2.0"
repository = "https://github.com/thscharler/rat-salsa"
readme = "readme.md"
keywords = ["ratatui", "focus"]
categories = ["command-line-interface"]
exclude = [".idea/*", ".gitignore"]

[features]
unstable-widget-ref = [
    "ratatui/unstable-widget-ref",
]

[dependencies]
ratatui = { version = "0.29" }
crossterm = "0.28"
unicode-segmentation = "1.11"
unicode-display-width = "0.3"

rat-event = { version = "1.0", path = "../rat-event" }
rat-focus = { version = "0.32", path = "../rat-focus" }
rat-popup = { version = "0.28", path = "../rat-popup" }

[dev-dependencies]